; This file was auto-generated by drush make
core = 7.x
api = 2

includes[remote] = "https://raw.githubusercontent.com/jpluijmers/drupal-makefiles/master/drupal-7-default.make"

projects[silver_arrows][type] = "profile"
projects[silver_arrows][download][type] = "git"
projects[silver_arrows][download][url] = "git@github.com:jpluijmers/distro-sa.git"